#!/bin/sh -e
# postinst script

# http://wiki.debian.org/Apache/PackagingModules
#if [ "$1" = configure ] ; then
    #invoke-rc.d apache2 restart
#fi
echo "You may restart your apache server now ..."
